### ISSUE TITLE
DevServer Assets (Images, YAML...etc) Updates

### ISSUE THREAD

**Issue by zaksparo** [callstack/react-native-webpack-toolkit#12]
Currently working on a consequent React Native app with the basic Metro Bundler, we commonly use some external assets that are imported as strings with the `babel-inline-import-plugin`.
**Example :** `import Foo from "./bar.yml"`.

The main pain point is that for reloading these assets, we regularly need to `reset-cache` during development stage in order to see these assets been updated in the app which is a **time consuming** and **demotivating** process.

Therefore and because of the Metro architecture, I never achieved to hot reload these assets using it. So I thought that by going through other bundler solution approaching the webpack logic like `haul` or this one, that would solve my issue.
But, after making things works (been able to launch the application through `webpack-toolkit` with devServer ...etc), this remains the same : I still have to relaunch the bundler (and reset cache if enabled) in order to update these assets.

After trying multiple remediations, the only extensions files that webpack watch/listen about for rebuilding is and always remains code `tsx?/jsx?` files

Maybe i'm seeing things from a wrong angle, so, if you can bring to me some help concerning this topic, it will be really appreciated.

Thank you in advance

**Comment by zamotany** [comment]
I assume the issue was resolved, but for anyone who encounters similar problem the solution is to use loaders - eg: https://webpack.js.org/loaders/raw-loader. With the use of loaders, Webpack in watch mode should listen for the changes to those files.
